  # Starter pipeline
  # Start with a minimal pipeline that you can customize to build and deploy your code.
  # Add steps that build, run tests, deploy, and more:
  # https://aka.ms/yaml


stages:
- stage: Test
  jobs:

  - job: FastenStaticAnalyzer_UnitTest
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'UnitTest'
    steps:
    - script: |
        ./install.sh
        python -m pip install -r requirements.txt
        python -m unittest


  - job: FastenStaticAnalyzer_Pylint
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Pylint'
    steps:
    - script: |
        ./install.sh
        python -m pip install -r requirements.txt
        python -m pip install pylint
        pylint --disable=R,C FastenStaticAnalyzer.py 


  - job: FastenStaticAnalyzer_SystemTest
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'SystemTest'
    steps:
    - script: |
        ./install.sh
        ./test_exec.sh

